# Use Maven with JDK 17 for building the application
FROM maven:3.8.4-openjdk-17 AS build
WORKDIR /app

# Copy the Maven project files
COPY pom.xml .
COPY src ./src

# Package the application without running tests
RUN mvn clean package -DskipTests -X

# Use OpenJDK 17 for running the application
FROM openjdk:17
WORKDIR /app

# Copy the packaged application from the build stage
COPY --from=build /app/target/backend-0.0.1-SNAPSHOT.jar /app/backend.jar

# Expose the port the application runs on
EXPOSE 8080

# Run the application
ENTRYPOINT ["java", "-jar", "backend.jar"]