version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: project
    ports:
      - "5432:5432"
    networks:
      - app-network

  frontend:
    build:
      context: ./../frontend
      dockerfile: ./../frontend/dockerfile
    ports:
      - "80:80"
    networks:
      - app-network

  backend:
    build:
      context: ./../backend
      dockerfile: ./../backend/dockerfile
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
    networks:
      - app-network

networks:
  app-network:
    driver: bridge